@baseUrl = http://localhost:3000
@jwttoken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MjExNmExZjc4ZjdlODFlMDA5ODgxN2UiLCJ1c2VybmFtZSI6ImtheW8yIiwiaWF0IjoxNjQ1MzgxMzQyLCJleHAiOjE2NDUzODE0MDJ9.zEz1GNwfcVYDaYJu2m3iQX7TUDNSUaF1Prb5z5EqGXQ

###
GET {{baseUrl}}/users HTTP/1.1

###
GET {{baseUrl}}/users/62112d1b2ccda808858fcadf HTTP/1.1

###
POST {{baseUrl}}/users HTTP/1.1
content-type: application/json

{
    "username": "kayo22",
    "password": "12!@21312aA",
    "active": false
}

###
PATCH {{baseUrl}}/users/62112d1b2ccda808858fcadf
content-type: application/json

{
    "username": "kayo",
    "password": "123456",
    "active": "0"
}


###
DELETE {{baseUrl}}/users/621148c4789112e987484b5c

###
POST {{baseUrl}}/auth/login HTTP/1.1
content-type: application/json

{
    "username": "kayo2",
    "password": "12!@21312aA"
}


###
DELETE {{baseUrl}}/users/delete/all HTTP/1.1
content-type: application/json
Authorization: {{jwttoken}}

///PROJECTS REQUESTS

###
GET  {{baseUrl}}/projects


###
GET {{baseUrl}}/projects/62126a039de8e5b859f594a6 HTTP/1.1

###
POST {{baseUrl}}/projects HTTP/1.1
content-type: application/json

{
    "name": "4444",
    "begin": "2021-02-02",
    "end": "2021-03-02",
    "description": "Teste",
    "active": false
}

@projectId = 62129373264f4f1921c29bcb
###
PATCH {{baseUrl}}/projects/62126a039de8e5b859f594a6
content-type: application/json

{
    "name": "4444",
    "end": "2021-03-02",
    "description": "Teste",
    "active": false
}

###
DELETE {{baseUrl}}/projects/62126a039de8e5b859f594a6

###
DELETE {{baseUrl}}/projects/delete/all HTTP/1.1
content-type: application/json
Authorization: {{jwttoken}}

///COLLABORATORS REQUESTS


###
GET  {{baseUrl}}/collaborators


###
GET {{baseUrl}}/collaborators/6212800cb40a16d6fbb4a002 HTTP/1.1

###
POST {{baseUrl}}/collaborators HTTP/1.1
content-type: application/json

{
    "name": "Testing Name2",
    "role": "aa",
    "admission": "2021-03-02",
    "active": true
}

@collaboratorId = 62129398264f4f1921c29bce
###
PATCH {{baseUrl}}/collaborators/6212800cb40a16d6fbb4a002
content-type: application/json

{
    "name": "Kayo Santana",
    "role": "Backend Developer",
    "admission": "2021-03-02",
    "active": true
}

###
DELETE {{baseUrl}}/collaborators/62128028b40a16d6fbb4a004

###
DELETE {{baseUrl}}/collaborators/delete/all HTTP/1.1
content-type: application/json
Authorization: {{jwttoken}}

///////COLABORATORS-PROJECT

###
GET  {{baseUrl}}/collaborators-projects


###
GET {{baseUrl}}/collaborators-projects/62129c16cbc4b4080ea9b6e2 HTTP/1.1

###
POST {{baseUrl}}/collaborators-projects HTTP/1.1
content-type: application/json

{
    "collaborator_id": "62129398264f4f1921c29bce",
    "project_id": "62129373264f4f1921c29bcb",
    "begin": "2002-03-16",
    "end": "2002-03-20"
}

PATCH {{baseUrl}}/collaborators-projects/6212800cb40a16d6fbb4a002
content-type: application/json

{
    "name": "Kayo Santana",
    "role": "Backend Developer",
    "admission": "2021-03-02",
    "active": true
}

###
DELETE {{baseUrl}}/collaborators-projects/62129c16cbc4b4080ea9b6e2

###
DELETE {{baseUrl}}/collaborators-projects/delete/all HTTP/1.1
content-type: application/json
Authorization: {{jwttoken}}


###
GET {{baseUrl}}/collaborators-projects/collaborator/62129398264f4f1921c29bce HTTP/1.1

###
GET {{baseUrl}}/collaborators-projects/project/62129373264f4f1921c29bcb HTTP/1.1